name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Build App
        run: cd go && CGO_ENABLED=0 go build -o demoapp main.go && cd ..
      - name: Upload demoapp binary
        uses: actions/upload-artifact@v2
        with:
          name: demoapp
          path: go/demoapp

  image:
    name: Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download demoapp binary
        uses: actions/download-artifact@v2
        with:
          name: demoapp
      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Init Packer Plugins
        run: packer init packer/app.pkr.hcl
      - name: Install Manual Packer Plugins
        run: |
          curl -L -o packer-provisioner-goss.tgz https://github.com/YaleUniversity/packer-provisioner-goss/releases/download/v3.0.3/packer-provisioner-goss-v3.0.3-linux-amd64.tar.gz
          tar zxf packer-provisioner-goss.tgz
          mv packer-provisioner-goss $HOME/.packer.d/plugins/
          sleep 30
      - name: Validate Template
        run: packer validate -syntax-only packer/app.pkr.hcl
      - name: Build Image
        run: packer build packer/app.pkr.hcl
        env:
          UPCLOUD_API_PASSWORD: ${{ secrets.UPCLOUD_API_PASSWORD }}
          UPCLOUD_API_USER: github

