name: build
on:
        push:
                branches:
                        - main

jobs:
        build:
                name: Build
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Setup Go
                          uses: actions/setup-go@v2
                          with:
                                  go-version: '^1.16.0'
                        - run: cd go && go build -o demoapp main.go

