name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Build App
        run: cd go && CGO_ENABLED=0 go build -o demoapp main.go && cd ..
      - name: Upload demoapp binary
        uses: actions/upload-artifact@v2
        with:
          name: app_binary
          path: go/demoapp

  image:
    name: Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download demoapp binary
        uses: actions/download-artifact@v2
        with:
          name: app_binary
          path: demoapp
      - name: Init Packer Plugins
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: packer/app.pkr.hcl
      - name: Install Manual Packer Plugins
        run: |
          curl -L -o packer-provisioner-goss.tgz https://github.com/YaleUniversity/packer-provisioner-goss/releases/download/v3.0.3/packer-provisioner-goss-v3.0.3-linux-amd64.tar.gz
          tar zxf packer-provisioner-goss.tgz
          mkdir -p ~/.packer.d/plugins
          mv packer-provisioner-goss ~/.packer.d/plugins
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/app.pkr.hcl
      - name: Build Image
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          target: packer/app.pkr.hcl
        env:
          PACKER_LOG: 1
          UPCLOUD_API_PASSWORD: ${{ secrets.UPCLOUD_API_PASSWORD }}
          UPCLOUD_API_USER: ${{ secrets.UPCLOUD_API_USER }}

